name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.6
        bundler-cache: true
        
    - name: Install dependencies
      run: bundle install
      
    - name: Set up database
      run: |
        mkdir -p db
        bundle exec rake db:migrate
        
    - name: Build application
      run: |
        echo "Application built successfully"
        echo "Ready for deployment to your preferred platform:"
        echo "- Heroku: git push heroku main"
        echo "- Railway: railway up"
        echo "- Fly.io: fly deploy"
        
    - name: Run health check
      run: |
        # Start server and test
        bundle exec rackup config.ru -p 4567 &
        SERVER_PID=$!
        sleep 5
        
        # Health check
        if curl -f http://localhost:4567/; then
          echo "✅ Health check passed"
        else
          echo "❌ Health check failed"
          exit 1
        fi
        
        kill $SERVER_PID